# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loader.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import block_pb2 as block__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='loader.proto',
  package='iroha.network.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0cloader.proto\x12\x13iroha.network.proto\x1a\x0b\x62lock.proto\"\x1f\n\rBlocksRequest\x12\x0e\n\x06height\x18\x01 \x01(\x04\"\x1c\n\x0c\x42lockRequest\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\x32\xa2\x01\n\x06Loader\x12M\n\x0eretrieveBlocks\x12\".iroha.network.proto.BlocksRequest\x1a\x15.iroha.protocol.Block0\x01\x12I\n\rretrieveBlock\x12!.iroha.network.proto.BlockRequest\x1a\x15.iroha.protocol.Blockb\x06proto3')
  ,
  dependencies=[block__pb2.DESCRIPTOR,])




_BLOCKSREQUEST = _descriptor.Descriptor(
  name='BlocksRequest',
  full_name='iroha.network.proto.BlocksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='iroha.network.proto.BlocksRequest.height', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=81,
)


_BLOCKREQUEST = _descriptor.Descriptor(
  name='BlockRequest',
  full_name='iroha.network.proto.BlockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='iroha.network.proto.BlockRequest.hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['BlocksRequest'] = _BLOCKSREQUEST
DESCRIPTOR.message_types_by_name['BlockRequest'] = _BLOCKREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlocksRequest = _reflection.GeneratedProtocolMessageType('BlocksRequest', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKSREQUEST,
  __module__ = 'loader_pb2'
  # @@protoc_insertion_point(class_scope:iroha.network.proto.BlocksRequest)
  ))
_sym_db.RegisterMessage(BlocksRequest)

BlockRequest = _reflection.GeneratedProtocolMessageType('BlockRequest', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKREQUEST,
  __module__ = 'loader_pb2'
  # @@protoc_insertion_point(class_scope:iroha.network.proto.BlockRequest)
  ))
_sym_db.RegisterMessage(BlockRequest)



_LOADER = _descriptor.ServiceDescriptor(
  name='Loader',
  full_name='iroha.network.proto.Loader',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=114,
  serialized_end=276,
  methods=[
  _descriptor.MethodDescriptor(
    name='retrieveBlocks',
    full_name='iroha.network.proto.Loader.retrieveBlocks',
    index=0,
    containing_service=None,
    input_type=_BLOCKSREQUEST,
    output_type=block__pb2._BLOCK,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='retrieveBlock',
    full_name='iroha.network.proto.Loader.retrieveBlock',
    index=1,
    containing_service=None,
    input_type=_BLOCKREQUEST,
    output_type=block__pb2._BLOCK,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOADER)

DESCRIPTOR.services_by_name['Loader'] = _LOADER

# @@protoc_insertion_point(module_scope)
