# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mst.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import block_pb2 as block__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mst.proto',
  package='iroha.network.transport',
  syntax='proto3',
  serialized_pb=_b('\n\tmst.proto\x12\x17iroha.network.transport\x1a\x0b\x62lock.proto\x1a\x1bgoogle/protobuf/empty.proto\"\'\n\x04Peer\x12\x0e\n\x06pubkey\x18\x01 \x01(\x0c\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"j\n\x08MstState\x12\x31\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x1b.iroha.protocol.Transaction\x12+\n\x04peer\x18\x02 \x01(\x0b\x32\x1d.iroha.network.transport.Peer2Z\n\x10MstTransportGrpc\x12\x46\n\tSendState\x12!.iroha.network.transport.MstState\x1a\x16.google.protobuf.Emptyb\x06proto3')
  ,
  dependencies=[block__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_PEER = _descriptor.Descriptor(
  name='Peer',
  full_name='iroha.network.transport.Peer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pubkey', full_name='iroha.network.transport.Peer.pubkey', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='iroha.network.transport.Peer.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=119,
)


_MSTSTATE = _descriptor.Descriptor(
  name='MstState',
  full_name='iroha.network.transport.MstState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transactions', full_name='iroha.network.transport.MstState.transactions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='peer', full_name='iroha.network.transport.MstState.peer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=227,
)

_MSTSTATE.fields_by_name['transactions'].message_type = block__pb2._TRANSACTION
_MSTSTATE.fields_by_name['peer'].message_type = _PEER
DESCRIPTOR.message_types_by_name['Peer'] = _PEER
DESCRIPTOR.message_types_by_name['MstState'] = _MSTSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Peer = _reflection.GeneratedProtocolMessageType('Peer', (_message.Message,), dict(
  DESCRIPTOR = _PEER,
  __module__ = 'mst_pb2'
  # @@protoc_insertion_point(class_scope:iroha.network.transport.Peer)
  ))
_sym_db.RegisterMessage(Peer)

MstState = _reflection.GeneratedProtocolMessageType('MstState', (_message.Message,), dict(
  DESCRIPTOR = _MSTSTATE,
  __module__ = 'mst_pb2'
  # @@protoc_insertion_point(class_scope:iroha.network.transport.MstState)
  ))
_sym_db.RegisterMessage(MstState)



_MSTTRANSPORTGRPC = _descriptor.ServiceDescriptor(
  name='MstTransportGrpc',
  full_name='iroha.network.transport.MstTransportGrpc',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=229,
  serialized_end=319,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendState',
    full_name='iroha.network.transport.MstTransportGrpc.SendState',
    index=0,
    containing_service=None,
    input_type=_MSTSTATE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MSTTRANSPORTGRPC)

DESCRIPTOR.services_by_name['MstTransportGrpc'] = _MSTTRANSPORTGRPC

# @@protoc_insertion_point(module_scope)
