# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import mst_pb2 as mst__pb2


class MstTransportGrpcStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendState = channel.unary_unary(
        '/iroha.network.transport.MstTransportGrpc/SendState',
        request_serializer=mst__pb2.MstState.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class MstTransportGrpcServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MstTransportGrpcServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendState': grpc.unary_unary_rpc_method_handler(
          servicer.SendState,
          request_deserializer=mst__pb2.MstState.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'iroha.network.transport.MstTransportGrpc', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
