# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import block_pb2 as block__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import proposal_pb2 as proposal__pb2


class OrderingGateTransportGrpcStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.onProposal = channel.unary_unary(
        '/iroha.ordering.proto.OrderingGateTransportGrpc/onProposal',
        request_serializer=proposal__pb2.Proposal.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class OrderingGateTransportGrpcServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def onProposal(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OrderingGateTransportGrpcServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'onProposal': grpc.unary_unary_rpc_method_handler(
          servicer.onProposal,
          request_deserializer=proposal__pb2.Proposal.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'iroha.ordering.proto.OrderingGateTransportGrpc', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class OrderingServiceTransportGrpcStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.onTransaction = channel.unary_unary(
        '/iroha.ordering.proto.OrderingServiceTransportGrpc/onTransaction',
        request_serializer=block__pb2.Transaction.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class OrderingServiceTransportGrpcServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def onTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OrderingServiceTransportGrpcServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'onTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.onTransaction,
          request_deserializer=block__pb2.Transaction.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'iroha.ordering.proto.OrderingServiceTransportGrpc', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
