# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ordering.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import block_pb2 as block__pb2
import proposal_pb2 as proposal__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ordering.proto',
  package='iroha.ordering.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0eordering.proto\x12\x14iroha.ordering.proto\x1a\x0b\x62lock.proto\x1a\x0eproposal.proto\x1a\x1bgoogle/protobuf/empty.proto2[\n\x19OrderingGateTransportGrpc\x12>\n\nonProposal\x12\x18.iroha.protocol.Proposal\x1a\x16.google.protobuf.Empty2d\n\x1cOrderingServiceTransportGrpc\x12\x44\n\ronTransaction\x12\x1b.iroha.protocol.Transaction\x1a\x16.google.protobuf.Emptyb\x06proto3')
  ,
  dependencies=[block__pb2.DESCRIPTOR,proposal__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ORDERINGGATETRANSPORTGRPC = _descriptor.ServiceDescriptor(
  name='OrderingGateTransportGrpc',
  full_name='iroha.ordering.proto.OrderingGateTransportGrpc',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=98,
  serialized_end=189,
  methods=[
  _descriptor.MethodDescriptor(
    name='onProposal',
    full_name='iroha.ordering.proto.OrderingGateTransportGrpc.onProposal',
    index=0,
    containing_service=None,
    input_type=proposal__pb2._PROPOSAL,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORDERINGGATETRANSPORTGRPC)

DESCRIPTOR.services_by_name['OrderingGateTransportGrpc'] = _ORDERINGGATETRANSPORTGRPC


_ORDERINGSERVICETRANSPORTGRPC = _descriptor.ServiceDescriptor(
  name='OrderingServiceTransportGrpc',
  full_name='iroha.ordering.proto.OrderingServiceTransportGrpc',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=191,
  serialized_end=291,
  methods=[
  _descriptor.MethodDescriptor(
    name='onTransaction',
    full_name='iroha.ordering.proto.OrderingServiceTransportGrpc.onTransaction',
    index=0,
    containing_service=None,
    input_type=block__pb2._TRANSACTION,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORDERINGSERVICETRANSPORTGRPC)

DESCRIPTOR.services_by_name['OrderingServiceTransportGrpc'] = _ORDERINGSERVICETRANSPORTGRPC

# @@protoc_insertion_point(module_scope)
