# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yac.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yac.proto',
  package='iroha.consensus.yac.proto',
  syntax='proto3',
  serialized_pb=_b('\n\tyac.proto\x12\x19iroha.consensus.yac.proto\x1a\x1bgoogle/protobuf/empty.proto\".\n\tSignature\x12\x0e\n\x06pubkey\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"f\n\x04Hash\x12\x10\n\x08proposal\x18\x01 \x01(\x0c\x12\r\n\x05\x62lock\x18\x02 \x01(\x0c\x12=\n\x0f\x62lock_signature\x18\x03 \x01(\x0b\x32$.iroha.consensus.yac.proto.Signature\"n\n\x04Vote\x12-\n\x04hash\x18\x01 \x01(\x0b\x32\x1f.iroha.consensus.yac.proto.Hash\x12\x37\n\tsignature\x18\x02 \x01(\x0b\x32$.iroha.consensus.yac.proto.Signature\"8\n\x06\x43ommit\x12.\n\x05votes\x18\x01 \x03(\x0b\x32\x1f.iroha.consensus.yac.proto.Vote\"8\n\x06Reject\x12.\n\x05votes\x18\x01 \x03(\x0b\x32\x1f.iroha.consensus.yac.proto.Vote2\xdc\x01\n\x03Yac\x12\x43\n\x08SendVote\x12\x1f.iroha.consensus.yac.proto.Vote\x1a\x16.google.protobuf.Empty\x12G\n\nSendCommit\x12!.iroha.consensus.yac.proto.Commit\x1a\x16.google.protobuf.Empty\x12G\n\nSendReject\x12!.iroha.consensus.yac.proto.Reject\x1a\x16.google.protobuf.Emptyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_SIGNATURE = _descriptor.Descriptor(
  name='Signature',
  full_name='iroha.consensus.yac.proto.Signature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pubkey', full_name='iroha.consensus.yac.proto.Signature.pubkey', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='iroha.consensus.yac.proto.Signature.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=115,
)


_HASH = _descriptor.Descriptor(
  name='Hash',
  full_name='iroha.consensus.yac.proto.Hash',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposal', full_name='iroha.consensus.yac.proto.Hash.proposal', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block', full_name='iroha.consensus.yac.proto.Hash.block', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_signature', full_name='iroha.consensus.yac.proto.Hash.block_signature', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=219,
)


_VOTE = _descriptor.Descriptor(
  name='Vote',
  full_name='iroha.consensus.yac.proto.Vote',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='iroha.consensus.yac.proto.Vote.hash', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='iroha.consensus.yac.proto.Vote.signature', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=331,
)


_COMMIT = _descriptor.Descriptor(
  name='Commit',
  full_name='iroha.consensus.yac.proto.Commit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='votes', full_name='iroha.consensus.yac.proto.Commit.votes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=389,
)


_REJECT = _descriptor.Descriptor(
  name='Reject',
  full_name='iroha.consensus.yac.proto.Reject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='votes', full_name='iroha.consensus.yac.proto.Reject.votes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=447,
)

_HASH.fields_by_name['block_signature'].message_type = _SIGNATURE
_VOTE.fields_by_name['hash'].message_type = _HASH
_VOTE.fields_by_name['signature'].message_type = _SIGNATURE
_COMMIT.fields_by_name['votes'].message_type = _VOTE
_REJECT.fields_by_name['votes'].message_type = _VOTE
DESCRIPTOR.message_types_by_name['Signature'] = _SIGNATURE
DESCRIPTOR.message_types_by_name['Hash'] = _HASH
DESCRIPTOR.message_types_by_name['Vote'] = _VOTE
DESCRIPTOR.message_types_by_name['Commit'] = _COMMIT
DESCRIPTOR.message_types_by_name['Reject'] = _REJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Signature = _reflection.GeneratedProtocolMessageType('Signature', (_message.Message,), dict(
  DESCRIPTOR = _SIGNATURE,
  __module__ = 'yac_pb2'
  # @@protoc_insertion_point(class_scope:iroha.consensus.yac.proto.Signature)
  ))
_sym_db.RegisterMessage(Signature)

Hash = _reflection.GeneratedProtocolMessageType('Hash', (_message.Message,), dict(
  DESCRIPTOR = _HASH,
  __module__ = 'yac_pb2'
  # @@protoc_insertion_point(class_scope:iroha.consensus.yac.proto.Hash)
  ))
_sym_db.RegisterMessage(Hash)

Vote = _reflection.GeneratedProtocolMessageType('Vote', (_message.Message,), dict(
  DESCRIPTOR = _VOTE,
  __module__ = 'yac_pb2'
  # @@protoc_insertion_point(class_scope:iroha.consensus.yac.proto.Vote)
  ))
_sym_db.RegisterMessage(Vote)

Commit = _reflection.GeneratedProtocolMessageType('Commit', (_message.Message,), dict(
  DESCRIPTOR = _COMMIT,
  __module__ = 'yac_pb2'
  # @@protoc_insertion_point(class_scope:iroha.consensus.yac.proto.Commit)
  ))
_sym_db.RegisterMessage(Commit)

Reject = _reflection.GeneratedProtocolMessageType('Reject', (_message.Message,), dict(
  DESCRIPTOR = _REJECT,
  __module__ = 'yac_pb2'
  # @@protoc_insertion_point(class_scope:iroha.consensus.yac.proto.Reject)
  ))
_sym_db.RegisterMessage(Reject)



_YAC = _descriptor.ServiceDescriptor(
  name='Yac',
  full_name='iroha.consensus.yac.proto.Yac',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=450,
  serialized_end=670,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendVote',
    full_name='iroha.consensus.yac.proto.Yac.SendVote',
    index=0,
    containing_service=None,
    input_type=_VOTE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendCommit',
    full_name='iroha.consensus.yac.proto.Yac.SendCommit',
    index=1,
    containing_service=None,
    input_type=_COMMIT,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendReject',
    full_name='iroha.consensus.yac.proto.Yac.SendReject',
    index=2,
    containing_service=None,
    input_type=_REJECT,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_YAC)

DESCRIPTOR.services_by_name['Yac'] = _YAC

# @@protoc_insertion_point(module_scope)
