# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import yac_pb2 as yac__pb2


class YacStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendVote = channel.unary_unary(
        '/iroha.consensus.yac.proto.Yac/SendVote',
        request_serializer=yac__pb2.Vote.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.SendCommit = channel.unary_unary(
        '/iroha.consensus.yac.proto.Yac/SendCommit',
        request_serializer=yac__pb2.Commit.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.SendReject = channel.unary_unary(
        '/iroha.consensus.yac.proto.Yac/SendReject',
        request_serializer=yac__pb2.Reject.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class YacServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendVote(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendCommit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendReject(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_YacServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendVote': grpc.unary_unary_rpc_method_handler(
          servicer.SendVote,
          request_deserializer=yac__pb2.Vote.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'SendCommit': grpc.unary_unary_rpc_method_handler(
          servicer.SendCommit,
          request_deserializer=yac__pb2.Commit.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'SendReject': grpc.unary_unary_rpc_method_handler(
          servicer.SendReject,
          request_deserializer=yac__pb2.Reject.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'iroha.consensus.yac.proto.Yac', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
